customhost = "database-1.c6ky2whsfrsd.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chinchunseng-employee"
customregion = "us-east-1"
